### ISSUE TITLE
where is the AVA_val.txt

### ISSUE THREAD

**Issue by ztt0821** [qzchenwl/neural-image-assessment#1]
with open(file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ztt/下载/neural-image-assessment-master920/images/AVA_val.txt'

I found such problem

**Comment by qzchenwl** [comment]
You can generate it yourself. It's part of AVA.txt.

For example `head -n 200000 AVA.txt`

**Comment by ztt0821** [comment]
Thank you for your help. So, I need to download the AVA.txt first? I just run the train.py

**Comment by qzchenwl** [comment]
You need to download the full dataset, not just AVA.txt

I download the dataset [here](http://academictorrents.com/details/71631f83b11d3d79d8f84efe0a7e12f0ac001460)
